services:
  - type: web
    name: crm-nuxt-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_8QhglCBN2ceS@ep-wild-mountain-a1f89brp-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXP_SEC
        value: "3600"
      - key: JWT_EXP_DYS
        value: "7d"
      - key: COOKIE_NAME
        value: "crm-auth-token"
    healthCheckPath: /