services:
  - type: web
    name: crm-nuxt-app
    env: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: crm-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXP_SEC
        value: "3600"
      - key: JWT_EXP_DYS
        value: "7d"
      - key: COOKIE_NAME
        value: "crm-auth-token"
    healthCheckPath: /
    
  - type: pserv
    name: crm-postgres
    env: postgresql
    plan: free
    databaseName: crm_nuxt
    databaseUser: crm_user